# -*- coding: utf-8 -*-
"""Meshroom_Collab_3d_photo_scan(Youtube).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DR9uSfWdWWyeMxvBMvWnYA3UXIfzWyf2

## Please make Copy of this script to your drive before you Execute anything
![alt text](https://)
"""

#download meshroom
!wget -N https://github.com/alicevision/meshroom/releases/download/v2019.1.0/Meshroom-2019.1.0-linux.tar.gz
!mkdir meshroom
!tar xzf Meshroom-2019.1.0-linux.tar.gz -C ./meshroom

#connect to your google drive
from google.colab import drive
drive.mount('/gdrive')

#process the images to 3d model
!./meshroom/Meshroom-2019.1.0/meshroom_photogrammetry --input '/gdrive/My Drive/Meshroom/Doll' --output '/gdrive/My Drive/Meshroom/Output_folder'